[package]
name = "praxis-test-utils"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
readme = "../../README.md"
publish = false

[features]
default = ["store-postgres", "callout-rustls"]
store-postgres = ["praxis-ai-apis/store-postgres", "praxis-ai-proxy/store-postgres"]
store-sqlite = ["praxis-ai-apis/store-sqlite", "praxis-ai-proxy/store-sqlite"]
store-all = ["store-postgres", "store-sqlite"]
callout-rustls = ["praxis-ai-apis/callout-rustls", "praxis-ai-proxy/callout-rustls"]
callout-native-tls = ["praxis-ai-apis/callout-native-tls", "praxis-ai-proxy/callout-native-tls"]
llmd-ext-proc = [
    "praxis-ai-proxy/llmd-ext-proc",
    "dep:praxis-ai-llmd-ext-proc",
    "dep:tokio-stream",
    "dep:tonic",
]
praxis-main = ["praxis-ai-proxy/praxis-main"]

[lints]
workspace = true

[dependencies]
arc-swap = { workspace = true }
base64 = { workspace = true }
praxis = { workspace = true }
praxis-ai-apis = { workspace = true }
praxis-ai-proxy = { workspace = true }
praxis-ai-llmd-ext-proc = { workspace = true, optional = true }
praxis-core = { workspace = true }
praxis-filter = { workspace = true }
praxis-protocol = { workspace = true }
h2 = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
hyper = { workspace = true }
hyper-util = { workspace = true }
rand = { workspace = true }
rcgen = { workspace = true }
reqwest = { workspace = true }
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
pingora-core = { workspace = true }
tokio = { workspace = true, features = ["rt", "net", "io-util", "time", "sync"] }
tokio-stream = { workspace = true, optional = true }
tonic = { workspace = true, optional = true }
tracing = { workspace = true }
url = { workspace = true }
futures = { workspace = true }
tokio-rustls = { workspace = true }
tokio-tungstenite = { workspace = true }
